language: scala
scala:
   - 2.12.13
   - 2.13.4

jdk:
 - oraclejdk11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION  clean coverage test coverageReport;

after_success:
  - bash <(curl -s https://codecov.io/bash)